apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ionos-ddns

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: ionos-dyndns
      app.kubernetes.io/component: dns-updater
